return {}
-- local lspconfig = require("lspconfig")
--
-- return {
--   {
--     "neovim/nvim-lspconfig",
--     ---@class PluginLspOpts
--     opts = {
--       servers = {
--         angularls = {
--           root_diir = function(fname)
--             local util = require("lspconfig.util")
--             return util.root_pattern("angular.json", "nx.json", "project.json")(fname)
--           end,
--           filetypes = { "typescript", "html", "typescriptreact", "typescript.tsx", "htmlangular" },
--         },
--         -- eslint = {
--         --   settings = {
--         --     workingDirectories = { mode = "auto" },
--         --     filetypes = { "javascript", "typescript", "html" },
--         --     format = true,
--         --   },
--         -- },
--       },
--       setup = {
--         angularls = function(_, opts)
--           opts.root_dir = lspconfig.util.root_pattern("angular.json", "nx.json", "project.json")
--         end,
--         -- eslint = function()
--         --   local function get_client(buf)
--         --     return LazyVim.lsp.get_clients({ name = "eslint", bufnr = buf })[1]
--         --   end
--         --
--         --   local formatter = LazyVim.lsp.formatter({
--         --     name = "eslint: lsp",
--         --     primary = false,
--         --     priority = 200,
--         --     filter = "eslint",
--         --   })
--         --
--         --   -- Use EslintFixAll on Neovim < 0.10.0
--         --   if not pcall(require, "vim.lsp._dynamic") then
--         --     formatter.name = "eslint: EslintFixAll"
--         --     formatter.sources = function(buf)
--         --       local client = get_client(buf)
--         --       return client and { "eslint" } or {}
--         --     end
--         --     formatter.format = function(buf)
--         --       local client = get_client(buf)
--         --       if client then
--         --         local diag = vim.diagnostic.get(buf, { namespace = vim.lsp.diagnostic.get_namespace(client.id) })
--         --         if #diag > 0 then
--         --           vim.cmd("EslintFixAll")
--         --         end
--         --       end
--         --     end
--         --   end
--         --
--         --   -- register the formatter with LazyVim
--         --   LazyVim.format.register(formatter)
--         -- end,
--       },
--     },
--   },
-- }
