[general]
import = ["~/.config/alacritty/tokyo_night.toml"]
[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
size = 14
[window]
option_as_alt = "OnlyLeft"
opacity = 0.95
[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\u001b\r" }]
